language: python
python:
    - "2.7"
    - "3.6"
install:
    - pip install coveralls pytest-cov
    - pip install -r requirements.txt
script: pytest --cov-report= --cov=pCRTree
after_success: coveralls
